use_frameworks!
platform :ios, '10.0'

target 'Jelly_Example' do
    pod 'Jelly' , :path => '../'
    pod "TouchVisualizer", '~> 4.0.0'

  target 'UnitTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
